FROM jetbrains/teamcity-server:latest-nanoserver-1709


#SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

#FROM microsoft/dotnet-framework-build:4.7.1-windowsservercore-1709

#RUN mkdir -p C:\ProgramData\jetbrains\teamcity\lib\jdbc ; \
#    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
#    Invoke-WebRequest https://github.com/Microsoft/mssql-jdbc/releases/download/v6.4.0/mssql-jdbc-6.4.0.jre8.jar -OutFile C:\ProgramData\jetbrains\teamcity\lib\jdbc\sqlserver-jre8.jar
	
